;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Weapon.Hamme",NewTagName="Weapon.Hammer")
+GameplayTagList=(Tag="Damage.Blunt",DevComment="")
+GameplayTagList=(Tag="Damage.Pierce",DevComment="")
+GameplayTagList=(Tag="Damage.Slash",DevComment="")
+GameplayTagList=(Tag="Item.Fuel",DevComment="")
+GameplayTagList=(Tag="Item.Resource.FiberSource",DevComment="")
+GameplayTagList=(Tag="Item.Resource.Stick",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Blunt",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Hatchet",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.Slash",DevComment="")
+GameplayTagList=(Tag="Weapon.Axe",DevComment="")
+GameplayTagList=(Tag="Weapon.Fist",DevComment="")
+GameplayTagList=(Tag="Weapon.Hammer",DevComment="")
+GameplayTagList=(Tag="Weapon.Hatchet",DevComment="")
+GameplayTagList=(Tag="Weapon.Knife",DevComment="")
+GameplayTagList=(Tag="Weapon.OneHanded",DevComment="")
+GameplayTagList=(Tag="Weapon.Shield",DevComment="")
+GameplayTagList=(Tag="Weapon.Spear",DevComment="")
+GameplayTagList=(Tag="Weapon.Sword",DevComment="")
+GameplayTagList=(Tag="Weapon.TwoHanded",DevComment="")

